name: "ntfy"
version: "2.15.0"
slug: "ntfy"
description: "Self-hosted notification service"
url: "https://github.com/binwiederhier/ntfy"
advanced: true
arch:
  - aarch64
  - amd64
stage: stable
init: false
startup: application
boot: auto
host_network: false
hassio_api: false
homeassistant_api: false
privileged: []
full_access: false
apparmor: true
auth_api: false
ingress: true
ingress_port: 8080
panel_icon: mdi:bell-ring
panel_title: ntfy
panel_admin: true
map:
  - backup:rw
  - data:rw
  - config:rw
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "ntfy web interface and API"
webui: "http://[HOST]:[PORT:8080]/"
options:
  port: 8080
  base_url: ""
  auth_file: ""
  auth_default_access: "read-write"
  cache_file: "/data/cache.db"
  log_level: "INFO"
  behind_proxy: false
  enable_signup: false
  enable_login: false
  enable_reservations: false
schema:
  port: "port"
  base_url: "str?"
  auth_file: "str?"
  auth_default_access: "list(deny-all|read-write|write-only|read-only)?"
  cache_file: "str"
  log_level: "list(TRACE|DEBUG|INFO|WARN|ERROR)"
  behind_proxy: "bool"
  enable_signup: "bool"
  enable_login: "bool"
  enable_reservations: "bool"
